### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by farishkash** [natalya-limareva/prj-rev-bwfs-dasmoto#1]
https://github.com/natalya-limareva/prj-rev-bwfs-dasmoto/blob/f09238d8c644533dad7e5d18499579b464b0e807/Dasmoto_s_Arts_and_Crafts(Unit2_Codeacademy)/index.html#L16

nobr is a non standard element in html.  It has never been approved and it should not be used.

From 2001 archives of w3

http://lists.w3.org/Archives/Public/www-html/2001Aug/0007.html

> <NOBR> cannot be deprecated as it has never been part of
> even transitional W3C HTML versions; it is purely 
> proprietory.  But, in any case, if universal browser support
> for alternatives were the condition for deprecation, nothing
> would ever get deprecated.  Complete removal has happened 
> in XHTML 1.1, has to be based on a reasonable time delay to 
> allow it to happen at all.

No sure on your decision on why to use this or where you found this to be acceptable to use.  This is a first for me, I am old enough to know the standards from 1990s but I can't recall the last time I saw this.

You can either use span or strong here.

**Comment by natalya-limareva** [comment]
Thanks for your advice, I've made adjustments. I used <strong>.
