### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by farishkash** [natalya-limareva/prj-rev-bwfs-dasmoto#2]
https://github.com/natalya-limareva/prj-rev-bwfs-dasmoto/blob/f09238d8c644533dad7e5d18499579b464b0e807/Dasmoto_s_Arts_and_Crafts(Unit2_Codeacademy)/resources/style.css#L3

Lots of font family repetition here.

Since the whole webpage uses the same font family you can apply this to the body tag instead and avoid repeating yourself.

.body {
font-family: Helvetica;
}

**Comment by natalya-limareva** [comment]
Thank you! I made it!
body {
font-family: Helvetica;
}
