### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [natalya-limareva/prj-rev-bwfs-dasmoto#3]
Overall met expectations

In this first project I look at two primary items with the main goal being to stop inefficient or bad practices early.

First is did you use divs, ids/classes to manage and organize your html content.

Good on this. Only issue with your html was that you use an element that was never part of the standard.

Second is your css efficient and non repetitive.
Good on this also.  Font family repetition is one of the most common mistakes in this first project.

To prepare you for the upcoming projects I like you to go to flexboxfroggy.com. See how far you can get, the later projects uses flexbox heavily and this will help you immensely.

**Comment by natalya-limareva** [comment]
Thank you!
